let validateOrder : ValidateOrder = 
  fun checkProductCodeExists checkAddressExists unvalidatedOrder -> 

    let orderId = ...
    let customerInfo = ...
    let shippingAddress = ...

    let orderLines = 
      unvalidatedOrder.Lines
      // convert each line using `toValidatedOrderLine`
      |> List.map (toValidatedOrderLine checkProductCodeExists)
    ...
